"""Add whatsapp integrations cloned voices and reseller models

Revision ID: 9dc82aa3e514
Revises: 0006
Create Date: 2026-06-29 12:18:36.558109
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9dc82aa3e514'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('volume', sa.String(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reseller_queries_id'), 'reseller_queries', ['id'], unique=False)
    op.create_table('cloned_voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voice_id')
    )
    op.create_index(op.f('ix_cloned_voices_id'), 'cloned_voices', ['id'], unique=False)
    op.create_index(op.f('ix_cloned_voices_org_id'), 'cloned_voices', ['org_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.create_index(op.f('ix_integrations_service_name'), 'integrations', ['service_name'], unique=False)
    op.create_table('whatsapp_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_numbers_agent_id'), 'whatsapp_numbers', ['agent_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_id'), 'whatsapp_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_org_id'), 'whatsapp_numbers', ['org_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_phone_number'), 'whatsapp_numbers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.drop_index('ix_call_runs_agent_id', table_name='call_runs')
    op.drop_index('ix_call_runs_org_id', table_name='call_runs')
    op.create_index(op.f('ix_call_runs_id'), 'call_runs', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_id'), 'campaign_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.drop_index('ix_credit_transactions_order_id', table_name='credit_transactions')
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_org_id'), 'credit_transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_razorpay_order_id'), 'credit_transactions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_id'), 'knowledge_base_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_id'), 'knowledge_base_documents', ['id'], unique=False)
    op.create_index(op.f('ix_org_members_id'), 'org_members', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_id'), 'phone_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_phone_numbers_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_org_members_id'), table_name='org_members')
    op.drop_index(op.f('ix_knowledge_base_documents_id'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_chunks_id'), table_name='knowledge_base_chunks')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_credit_transactions_razorpay_order_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_org_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.create_index('ix_credit_transactions_order_id', 'credit_transactions', ['razorpay_order_id'], unique=True)
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaign_contacts_id'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_call_runs_id'), table_name='call_runs')
    op.create_index('ix_call_runs_org_id', 'call_runs', ['org_id'], unique=False)
    op.create_index('ix_call_runs_agent_id', 'call_runs', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_whatsapp_numbers_phone_number'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_org_id'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_id'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_agent_id'), table_name='whatsapp_numbers')
    op.drop_table('whatsapp_numbers')
    op.drop_index(op.f('ix_integrations_service_name'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_cloned_voices_org_id'), table_name='cloned_voices')
    op.drop_index(op.f('ix_cloned_voices_id'), table_name='cloned_voices')
    op.drop_table('cloned_voices')
    op.drop_index(op.f('ix_reseller_queries_id'), table_name='reseller_queries')
    op.drop_table('reseller_queries')
    # ### end Alembic commands ###
